build:
    cargo build --release --target=wasm32-unknown-unknown
    cp ./target/wasm32-unknown-unknown/release/req_channel_component.wasm ../../build/
debug:
    cargo build --target=wasm32-wasi
    cp ./target/wasm32-wasi/debug/req_channel_component.wasm ../../build/