wasm:
    mkdir -p build
    just wasm/reqres-component/build
    just wasm/baseline/build

debug:
    mkdir -p build
    just wasm/reqres-component/debug
    just wasm/baseline/debug

test:
  cargo test --workspace