build: codegen
    cargo build --release --target=wasm32-unknown-unknown
    cp ./target/wasm32-unknown-unknown/release/grabbag.wasm ../../build/
debug: codegen
    cargo +nightly build --target=wasm32-wasi
    cp ./target/wasm32-wasi/debug/grabbag.wasm ../../build/
codegen:
  apex generate
clean:
  cargo clean
