build:
    cargo build --release --target=wasm32-unknown-unknown
    cp ./target/wasm32-unknown-unknown/release/*.wasm ../../build/
debug:
    cargo build --target=wasm32-wasi
    cp ./target/wasm32-wasi/debug/*.wasm ../../build/
clean:
  cargo clean
