[package]
name = "wasmrs-rsocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmrs-ringbuffer = { path = "../wasmrs-ringbuffer" }

[dev-dependencies]
anyhow = { version = "1.0" }
