build: codegen
    cargo build --release --target=wasm32-unknown-unknown
    cp ./target/wasm32-unknown-unknown/release/reqres_component.wasm ../../build/
debug: codegen
    cargo build --target=wasm32-wasi
    cp ./target/wasm32-wasi/debug/reqres_component.wasm ../../build/
codegen:
  apex generate -r